return {
	Bag = require(script.Bag),
	Party = require(script.Party),
    Vault = require(script:WaitForChild("Vault")),
	CreatureViewer = require(script:WaitForChild("CreatureViewer")),
	Dex = require(script:WaitForChild("Dex")),
	Caught = require(script:WaitForChild("Caught")),
	Save = require(script.Save),
	Settings = require(script.Settings),
	TopBar = require(script.TopBar):Create(),
	PlayerList = require(script.PlayerList),
	NameInput = require(script:WaitForChild("NameInput")),
	CatchCareShop = require(script:WaitForChild("CatchCareShop")),
	BadgeAnimation = require(script:WaitForChild("BadgeAnimation")),
	CurrentRequest = require(script:WaitForChild("CurrentRequest")),
	Trade = require(script:WaitForChild("Trade")),
	WorldInfo = require(script:WaitForChild("WorldInfo")),
	AdminPanel = require(script:WaitForChild("AdminPanel")),
	Shop = require(script:WaitForChild("Shop")),
}